#ifndef PINS_DEFINITION_H
#define PINS_DEFINITION_H

// MTORO 1
#define MOTOR_1_ENABLE_PIN 13
#define MOTOR_1_PIN_1 12
#define MOTOR_1_PIN_2 14
// MOTOR 2
#define MOTOR_2_ENABLE_PIN 27
#define MOTOR_2_PIN_1 26
#define MOTOR_2_PIN_2 25

// SENSOR DHT- TEMPERATURA/HUMEDAD
#define DHT_SENSOR_TYPE DHT22
#define DHT_SENSOR_PIN 33

// modulo de 4 relays
#define VENTILADOR_PIN 22
#define FOCO_PIN 21
#define PLACA_TERMICA_PIN 19
#endif